config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/resume' => "welcome#resume"

  get '/projects/tictactoe' => "welcome#tictactoe"
  get '/projects/petnet' => "welcome#petnet"
  get '/projects/muziqala' => "welcome#muziqala"
  get '/projects/applied_meaning' => "welcome#applied_meaning"
  get '/projects/firenza' => "welcome#firenza"
  get '/projects/react_cats' => "welcome#react_cats"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Kate Wood - Web Developer</title>

	<%= favicon_link_tag 'main.jpg' %>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

</head>

<body>

<%= yield %>

</body>
</html>

app/views/welcome/_aboutme.html.erb
<div class="col-lg-12 container about">
	<h1>About Me</h1>
	<hr class="star-light">
	<h3>
		I am a front end developer with a passion for JavaScript, jQuery, and React. I love problem solving, debugging, and building awesome web apps! As an experienced technical instructor, I’m passionate about mentoring other developers and helping them hone their skills.
	</h3>
	<hr class="star-light">
	<%= link_to "View my resume", resume_path %>
</div>

app/views/welcome/_contact.html.erb
<div class="col-lg-12 container contact">
	<br><br>
	<h2>Contact Me!</h2>
	<br>
	<h4><span class="glyphicon glyphicon-envelope"></span> <%= mail_to 'katekodes@gmail.com', 'Email' %></h4>
	<br>
	<h4><span class="icon-logo linkedin"></span> <%= link_to 'LinkedIn Profile', 'https://www.linkedin.com/in/katewood611', :target => "_blank" %></h4>
	<br>
	<h4><span class="icon-logo github"></span> <%= link_to 'GitHub Profile', 'https://github.com/KateWood', :target => "_blank" %></h4>
	<br>
	<h4><span class="icon-logo ga"></span> <%= link_to 'GA Profile', 'https://profiles.generalassemb.ly/katewood', :target => "_blank" %></h4>
</div>

app/views/welcome/_home.html.erb
<div class="col-lg-12 container">
  <h3>I'm currently updating my portfolio site and rebuilding it in React.</h3>
  <h3>Come back in April to see it!</h3>
	<%= image_tag "main.jpg", :class => "img-responsive main-img" %>
	<br>
	<h1>Kate Wood</h1>
	<hr class="star-light">
	<h2>Front End Web Developer</h2>
</div>

app/views/welcome/_navbar.html.erb
<nav class="nav navbar nav-pink navbar-fixed-top">
	<div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar purple"></span>
			<span class="icon-bar purple"></span>
			<span class="icon-bar purple"></span>
			</button>
			<a class="navbar-brand" href="/"><span class="icon"><%= image_tag "main.jpg", :class => "icon" %></span>  Back to Main Page</a>
		</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/resume">R&eacute;sum&eacute;</a></li>
				<li class="dropdown">
					<a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="/projects/firenza">Firenza</a></li>
						<li><a href="/projects/react_cats">React Cats</a></li>
						<li><a href="/projects/applied_meaning">Applied Meaning</a></li>
						<li><a href="/projects/petnet">Petnet</a></li>
						<li><a href="/projects/tictactoe">Tic-Tac-Toe</a></li>
						<li><a href="/projects/muziqala">Muziqala</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/welcome/_portfolio.html.erb
<div class="col-lg-12 container">
	<br><br>
	<h1>Portfolio</h1>
	<p><em>Click on a screenshot to see more information on the project</em></p>
	<%= link_to projects_firenza_path do %>
		<div class="col-sm-5 portfolio-item firenza">
		</div>
	<% end %>
	<div class="col-sm-2"></div>
	<%= link_to projects_react_cats_path do %>
		<div class="col-sm-5 portfolio-item cats">
		</div>
	<% end %>
	<%= link_to projects_applied_meaning_path do %>
		<div class="col-sm-5 portfolio-item applied">
		</div>
	<% end %>
<div class="col-sm-2"></div>
	<%= link_to projects_petnet_path do %>
		<div class="col-sm-5 portfolio-item petnet">
		</div>
	<% end %>
	<%= link_to projects_tictactoe_path do %>
		<div class="col-sm-5 portfolio-item ttt">
		</div>
	<% end %>
	<div class="col-sm-2"></div>
	<%= link_to projects_muziqala_path do %>
		<div class="col-sm-5 portfolio-item muziqala">
		</div>
	<% end %>
</div>

app/views/welcome/_resume.html.erb
<div class="container">
	<h1>R&eacute;sum&eacute;</h1>
	<span id="respic">
		<%= image_tag 'default.jpg' %>
	</span>

	<h2><span class="glyphicon glyphicon-education"></span> Education</h2>
	<br>
	<h4>General Assembly - Web Development Immersive (WDI) | Apr 2015 - Jul 2015 | Santa Monica, CA</h4>
	<p>I went into WDI not knowing if I would like coding, but I ended up LOVING it! I found the lessons to be informative and exciting; I couldn't get enough. Now that the course has ended, I'm still excited to continue to be part of the GA community as a TA or mentor. I have made so many wonderful friends and learned so many amazing things that I would certainly describe WDI as one of the best and most fulfilling experiences of my life.</p>

	<br>
	<h4>New York University (B.F.A. in Film & Television) | Sep 2004 - Oct 2005 & May 2010 - Dec 2011 | New York, NY</h4>
	<p>I studied film and television in college and moved to Los Angeles to pursue a career as a television writer. Although I have not gotten that job, I have had many wonderful experiences in California, and my path has lead me to coding, which I really enjoy.</p>

	<br>
	<h2><span class="glyphicon glyphicon-briefcase"></span> Previous Employment</h2>
	<br>
	<h4>Administrative Temp at Apple One (Temp Agency) | Jun 2013 - Apr 2015 | Santa Clarita, CA</h4>
	<p>I was assigned to several different temporary positions during my time with Apple One. These positions ranged from receptionist to claims clerk to customer service representative. In these positions I spent most of my time working on a computer (Excel, Word, Outlook), answering phones (speaking with customers), and doing miscellaneous tasks for my supervisor, such as making copies, filing, and faxing.</p>

	<br>
	<h4>Social Media Consultant at Zinga! World's Best Frozen Yogurt | Mar 2011 - Jun 2013 | Santa Clarita, CA</h4>
	<p>While working for Zinga, I created instructional social media videos for franchisees, created and maintained the official Operations Manual, created and maintained other manuals specific to this company, edited the company website, acted as an administrator of the company's Facebook page, responded to customer concerns and promoted new store openings online.</p>

	<br>
	<h4>Administrative Aid at Jersey Mike's (Corporate Office) | Jul 2009 - Oct 2009 | Point Pleasant, NJ</h4>
	<p>During my 3-month contract with Jersey Mike's, I editing their Operations and Safety Manuals, and I created an employee manual for the "Team Washington" area director.</p>

	<br>
	<h4>Office Assistant/Payroll Clerk at Daventures, Ltd. | Aug 2007 - Feb 2008 | Manassas, VA</h4>
	<p>At Daventures, I processed bi-weekly payroll for 300+ employees, managed accounts receivable, ordered office supplies, processed new hires, answered phones, sent faxes, sorted and distributed mail, sent mail for supervisors, and assisted supervisors with various tasks upon request. <br>
	I returned to this position in January 2010 until May 2010, as a temporary fill-in before I returned to college to finish my degree.</p>

	<br>
	<h2><span class="glyphicon glyphicon-ok"></span> Skills</h2>
	<br>
	<h4>Coding Language Proficiency</h4>
	<p>Ruby | Rails | Postgresql | JavaScript | Angular.js | HTML | CSS | Bootstrap | RSpec | Factory Girl | Capybara | Travis-CI | Firebase | Heroku</p>

	<br>
	<h4>Additional Skills</h4>
	<p>Creative thinking | Problem solving | Proofreading | Comedy writing | Microsoft Office | Strong math skills | Organizational skills | Fast learner | Friendly | Professional | Personable | Mensa member</p>

	<br>
	<h2><span class="glyphicon glyphicon-file"></span> References available upon request</h2>

	<br>
	<h2><span class="glyphicon glyphicon-user"></span> Contact</h2>
	<br>
	<h4><%= mail_to 'katekodes@gmail.com', 'Email' %> | 
	<%= link_to 'LinkedIn Profile', 'https://www.linkedin.com/in/katewood611' %> | 
	<%= link_to 'GitHub Profile', 'https://github.com/KateWood' %> | 
	<%= link_to 'GA Profile', 'https://profiles.generalassemb.ly/katewood' %></h4>
</div>

app/views/welcome/firenza.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<%= render 'navbar' %>

<div class="container">
	<h3>Freelance Project: Firenza Pizza Franchise Website</h3>

	<p>This is a website where prospective franchisees can get information on Firenza Pizza and submit a contact form to request more information.</p>

	<%= link_to 'Firenza project on Github', 'https://github.com/KateWood/myfirenza', :target => "_blank" %>

	<h4>Technologies:</h4>

	<ul>
		<li>HTML/CSS</li>
		<li>Bootstrap</li>
		<li>PostgreSQL</li>
		<li>Ruby on Rails</li>
		<li>DigitalOcean (Ubuntu)</li>
		<li>Google Domains/DNS</li>
		<li>Postfix</li>
		<li>SPF/DKIM</li>
	</ul>

	<em>Click on any of the images below to go to the deployed version of myfirenza.com.</em>

	<h4>Landing Page</h4>
	<%= link_to (image_tag 'myfirenzafullpage.png'), 'http://www.myfirenza.com', :class => "linkpic", :target => "_blank" %>

	<h4>Index of Inquiries</h4>
	<p>Logged in users can view all contact form submissions here.</p>
	<%= link_to (image_tag 'myfirenzaindex.png'), 'http://www.myfirenza.com', :class => "linkpic", :target => "_blank" %>

	<h4>Inquiry Show Page</h4>
	<p>Logged in users can view individual contact form submissions here.</p>
	<%= link_to (image_tag 'myfirenzainquiry.png'), 'http://www.myfirenza.com', :class => "linkpic", :target => "_blank" %>

	<h4>Alert</h4>
	<p>Email sent to company when contact form is submitted.</p>
	<%= link_to (image_tag 'myfirenzaalert.png'), 'http://www.myfirenza.com', :class => "linkpic", :target => "_blank" %>

</div>

app/views/welcome/index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<nav class="nav navbar nav-pink navbar-fixed-top">
	<div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar purple"></span>
			<span class="icon-bar purple"></span>
			<span class="icon-bar purple"></span>
			</button>
			<a class="navbar-brand" href="#home"><span class="icon hidden-xs"><%= image_tag "main.jpg", :class => "icon" %></span>  Kate Wood - Web Developer</a>
		</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#portfolio">Portfolio</a></li>
				<li><a href="#about">About</a></li>
				<li><a href="#contact">Contact</a></li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<div class="stripe" id="home">
	<%= render 'home' %>
</div>

<div class="stripe" id="portfolio">
	<%= render 'portfolio' %>
</div>

<div class="stripe" id="about">
	<%= render 'aboutme' %>
</div>

<div class="stripe" id="contact">
	<%= render 'contact' %>
</div>

app/views/welcome/muziqala.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<%= render 'navbar' %>

<div class="container">
	<h3>Project 3: Muziqala</h3>

	<p>Muziqala is a new way to access music from Spotify, and see what music your friends are listening to. All users can add songs to public playlists that everyone else can access and listen to.</p>

	<%= link_to 'Muziqala on Github', 'https://github.com/KateWood/muziqala', :target => "_blank" %>

	<h4>Technologies:</h4>

	<ul>
		<li>HTML/CSS</li>
		<li>Bootstrap</li>
		<li>Ruby on Rails</li>
		<li>Spotify API</li>
		<li>PostgreSQL</li>
		<li>RSpec</li>
		<li>Factory Girl</li>
		<li>Capybara</li>
		<li>Travis-CI</li>
		<li>Heroku</li>
	</ul>

	<em>Click on any of the images below to go to the deployed version of Muziqala.</em>

	<h4>Landing Page</h4>
	<%= link_to (image_tag 'muziqalalanding.png'), 'https://muziqala.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>User's Profile</h4>
	<%= link_to (image_tag 'muziqalaprofile.png'), 'https://muziqala.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>Playlist</h4>
	<%= link_to (image_tag 'muziqalaplaylist.png'), 'https://muziqala.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>Readme</h4>
	<%= link_to (image_tag 'muziqalareadme.png'), 'https://muziqala.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

</div>

app/views/welcome/old_index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		<li data-target="#carousel-example-generic" data-slide-to="3"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<%= link_to (image_tag 'tictactoe.png'), '/projects/1' %>
		</div>
		<div class="item">
			<%= link_to (image_tag 'petnet.png'), '/projects/2' %>
		</div>
		<div class="item">
			<%= link_to (image_tag 'muziqala.png'), '/projects/3' %>
		</div>
		<div class="item">
			<%= link_to (image_tag 'applied_meaning.png'), '/projects/4' %>
		</div>
	</div>

	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

app/views/welcome/petnet.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<%= render 'navbar' %>

<div class="container">
	<h3>Project 2: Petnet</h3>

	<p>Have you ever gotten a Facebook friend request from a dog? Do you maintain a Facebook profile for your pet? Silly pets, Facebook is for people. Pets deserve their own social network! Enter <em>Petnet</em>, a social newtork for pets and the parents who love them.<br>Pet parents can sign up for an account, and then create profiles for all of their fur babies. Pets can create blog posts, which pet parents can comment on.</p>

	<%= link_to 'Petnet on Github', 'https://github.com/KateWood/petnet', :target => "_blank" %>

	<h4>Technologies:</h4>

	<ul>
		<li>HTML/CSS</li>
		<li>Bootstrap</li>
		<li>Ruby on Rails</li>
		<li>PostgreSQL</li>
		<li>Heroku</li>
	</ul>

	<em>Click on any of the images below to go to the deployed version of Petnet.</em>

	<h4>Landing Page</h4>
	<%= link_to (image_tag 'petnetlanding.png'), 'https://gapetnet.herokuapp.com', :class => "linkpic", :target => "_blank" %>

	<h4>User's Profile</h4>
	<%= link_to (image_tag 'petnetparent.png'), 'https://gapetnet.herokuapp.com', :class => "linkpic", :target => "_blank" %>

	<h4>List of All Pets</h4>
	<%= link_to (image_tag 'petnetpets.png'), 'https://gapetnet.herokuapp.com', :class => "linkpic", :target => "_blank" %>

	<h4>Pet's Profile</h4>
	<%= link_to (image_tag 'petnetpetprofile.png'), 'https://gapetnet.herokuapp.com', :class => "linkpic" %>

	<h4>Pet's Post</h4>
	<%= link_to (image_tag 'petnetpost.png'), 'https://gapetnet.herokuapp.com', :class => "linkpic", :target => "_blank" %>

	<h4>Readme</h4>
	<%= link_to (image_tag 'petnetreadme.png'), 'https://gapetnet.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

</div>

app/views/welcome/react_cats.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<%= render 'navbar' %>

<div class="container">
	<h3>Personal Project: React Cats</h3>

	<p>This is a website where users can see random cat pictures.</p>

	<%= link_to 'React Cats on Github', 'https://github.com/KateWood/react_cats', :target => "_blank" %>

	<h4>Technologies:</h4>

	<ul>
		<li>HTML/CSS</li>
		<li>Foundation</li>
		<li>SASS</li>
		<li>React</li>
		<li>Node</li>
		<li>Express</li>
		<li>MongoDB</li>
		<li>Heroku</li>
	</ul>

	<em>Click on the image below to go to the deployed version of React Cats.</em>

	<h4>Cat Page</h4>
	<%= link_to (image_tag 'cat.png'), 'http://react-cats.herokuapp.com/', :class => "linkpic", :target => "_blank" %>

</div>

app/views/welcome/tictactoe.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69400624-1', 'auto');
  ga('send', 'pageview');

</script>

<%= render 'navbar' %>

<div class="container">
	<h3>Project 1: Tic-Tac-Toe</h3>

	<p>This <em>Fire & Ice</em> themed Tic-Tac-Toe game is a two-player game which updates the screen for both players as each player takes his/her turn.<br>Each player may only choose a square on his/her turn, and the game ends when someone wins or all of the spaces are taken with no winner.</p>

	<%= link_to 'Tic-Tac-Toe on Github', 'https://github.com/KateWood/project_1', :target => "_blank" %>

	<h4>Technologies:</h4>

	<ul>
		<li>HTML/CSS</li>
		<li>Javascript</li>
		<li>Angular.js</li>
		<li>Firebase</li>
	</ul>

	<em>Click on any of the images below to go to the deployed version of my Tic-Tac-Toe. To experience all of the features, open the site in two browser windows side-by-side.</em>

	<h4>Landing Page</h4>
	<%= link_to (image_tag 'tictactoelanding.png'), 'https://tictactoekate.firebaseapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>First Player's View</h4>
	<%= link_to (image_tag 'tttfire.png'), 'https://tictactoekate.firebaseapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>Second Player's View</h4>
	<%= link_to (image_tag 'tttice.png'), 'https://tictactoekate.firebaseapp.com/', :class => "linkpic", :target => "_blank" %>

	<h4>Readme</h4>
	<%= link_to (image_tag 'tttreadme.png'), 'https://tictactoekate.firebaseapp.com/', :class => "linkpic", :target => "_blank" %>

</div>